[package]
name = "rusty-html"
version = "0.1.0"
edition = "2021"
authors = ["Michael van Straten"]
description = "This crate allows for Jsx html inline like syntax in rust"
repository = "https://github.com/michaelvanstraten/rusty-html"
license = "MIT"

[dependencies]
rusty-html-macros = "^0.1"