[package]
name = "rusty-html-traits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty-html = { path = "../." }
#typed-html = "0.2.1"